---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: CLEAN FACTS FOLDER
      shell: rm -rf facts/*

- hosts: all
  gather_facts: yes
  connection: network_cli
  tasks:
    - name: SAVE DEVICE FACTS
      local_action: copy content={{[ansible_facts]}} dest=facts/{{ansible_net_hostname}}.json

- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: GENERATE JSON FILE
      command: python build_topology.py

    - name: READ JSON FILE
      shell: cat network_graph.json
      register: result

    - name: BUILD HTML FILE
      template:
        src: templates/html.j2
        dest: index.html

    - name: OPEN HTML FILE
      shell: open index.html

